#pragma once

/********************************************************/
/* 타일 정보 정의											*/
/* 작업자 : 이호형										*/
/********************************************************/

#define TILE_SIZEX		32
#define TILE_SIZEY		32


// 지형 속성
enum TERRAIN
{
	TR_GRASS, TR_DESERT, TR_SNOW, TR_WATER, TR_SWAMP,
	TR_GRAYSTONE, TR_WHITESTONE, TR_SOIL, TR_MUD,
	TR_ROAD, TR_DIRT, TR_STUMP, TR_BLOCKTILE, TR_WALL,
	TR_NONE
};

enum OBJECT
{
	OBJ_MOUNTAIN, OBJ_TREE, OBJ_CAVE, OBJ_TOWN, OBJ_CASTLE, OBJ_NPC, OBJ_ENEMY,
	OBJ_HOUSE_TOP, OBJ_HOUSE_BOTTOM, OBJ_HOUSE_BOT_PASS,
	OBJ_SIGNBOARD, OBJ_TOMBSTONE, OBJ_PLANT, OBJ_WELL_TOP, OBJ_WELL_BOTTOM,
	OBJ_BRIDGE_TOP, OBJ_BRIDGE_BOTTOM, OBJ_TREE_TOP, OBJ_TREE_BOTTOM,
	OBJ_STALL_TOP, OBJ_STALL_BOTTOM, OBJ_TENT, OBJ_FIREWOOD, OBJ_SACK, OBJ_VASE,
	OBJ_NONE
};

enum ATTRIBUTE
{
	ATTR_UNMOVE, ATTR_SLOW, ATTR_FAST,
	ATTR_AFTER_RENDER, ATTR_MOVE
};
